#!/usr/bin/env bash
set -euo pipefail

# Build the Constructive-Transformer paper PDF from markdown source.
# Usage:  ./paper/scripts/build_paper.sh [--skip-figures]
#
# Layout follows the truthspace_paper conventions:
#   - paper/paper.md            (single-source markdown with YAML front-matter)
#   - paper/scripts/preamble.tex (pandoc include-in-header, twocolumn-aware)
#   - output/figures/*.png      (generated by output/code/generate_figures.py)
#   - paper/paper.pdf           (final artifact, written next to paper.md)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAPER_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(dirname "$PAPER_DIR")"
OUTPUT_DIR="$PROJECT_DIR/output"

echo "=== Building The Constructive Transformer paper ==="

# Pick a Python that has numpy + matplotlib for figure regeneration.
# Override with FIG_PY=/path/to/python; otherwise we probe common venvs.
pick_fig_py() {
    if [ -n "${FIG_PY:-}" ] && "$FIG_PY" -c "import matplotlib, numpy" 2>/dev/null; then
        echo "$FIG_PY"; return
    fi
    for cand in "$PROJECT_DIR/../venv/bin/python" \
                "$PROJECT_DIR/.venv/bin/python" \
                "$HOME/.venv/bin/python3" \
                python3; do
        if command -v "$cand" >/dev/null 2>&1 \
           && "$cand" -c "import matplotlib, numpy" 2>/dev/null; then
            echo "$cand"; return
        fi
    done
    echo "python3"
}

# Step 1: Regenerate figures (optional, skip with --skip-figures)
if [ "${1:-}" != "--skip-figures" ]; then
    FIG_PY_RESOLVED="$(pick_fig_py)"
    echo "[1/4] Regenerating figures (using $FIG_PY_RESOLVED)..."
    "$FIG_PY_RESOLVED" "$OUTPUT_DIR/code/generate_figures.py" \
        2>&1 | sed 's/^/  /'
    echo "  Done."
else
    echo "[1/4] Skipping figure regeneration."
fi

# Step 2: Code demos are self-contained.
echo "[2/4] Code demos are self-contained (no build step)."

# Step 3: Prepare a build copy of paper.md with figure paths resolved.
#         pandoc is run from PAPER_DIR, so 'output/figures/foo.png' in the
#         source needs to become '../output/figures/foo.png' for the build.
echo "[3/4] Preparing build copy of paper.md..."
BUILD_MD="$PAPER_DIR/paper.build.md"
python3 - "$PAPER_DIR/paper.md" "$BUILD_MD" <<'PYPREP'
import re, sys
src = open(sys.argv[1]).read()
# Rewrite figure refs so pandoc (cwd = paper/) can resolve them.
src = src.replace('](output/figures/', '](../output/figures/')
# Replace LaTeX-unsafe Unicode glyphs that DejaVu Serif doesn't ship.
replacements = {
    '\u2502': '|', '\u2500': '-', '\u250c': '+', '\u2510': '+',
    '\u2514': '+', '\u2518': '+',
}
for ch, latex in replacements.items():
    src = src.replace(ch, latex)
open(sys.argv[2], 'w').write(src)
PYPREP
echo "  Done."

# Step 4: Compile PDF with pandoc + xelatex (two-stage so we can fix
# pandoc's longtable output to work inside twocolumn).
echo "[4/4] Compiling paper.pdf..."
cd "$PAPER_DIR"

# 4a: pandoc -> .tex (standalone)
pandoc paper.build.md \
    --from markdown \
    --to latex \
    --standalone \
    --include-in-header="$SCRIPT_DIR/preamble.tex" \
    -V mainfont="DejaVu Serif" \
    -V monofont="DejaVu Sans Mono" \
    -o paper.tex

# 4b: rewrite longtable blocks for twocolumn compatibility (identical
# logic to truthspace_paper/scripts/build_paper.sh).  See comments in
# that file for the full rationale; in short: longtable is not legal
# inside the twocolumn class, so each table is converted to a
# tabularx wrapped in a tsxtable centring environment; figure floats
# are widened to figure*; long \texttt paths get \seqsplit; and a
# \FloatBarrier is inserted before every chapter-level section.
python3 - <<'PYFIX'
import re
src = open('paper.tex').read()

# Step A: Drop the misplaced \bottomrule\noalign{} immediately after
# \endhead inside every longtable block.
src = re.sub(
    r'(\\endhead\s*\n)\\bottomrule\\noalign\{\}\s*\n\\endlastfoot\s*\n',
    r'\1',
    src,
)

# Step B: Rewrite each \begin{longtable}[]{@{}<spec>@{}} block as a
# tabularx wrapped in tsxtable.  Plain l/c/r specs are mapped to Y
# (auto-wrapping raggedright X).
def _rewrite_longtable(m):
    inner = m.group(1)
    body  = m.group(2)
    if 'p{' in inner or '>{' in inner or 'X' in inner:
        new_inner = inner.replace(r'\columnwidth', r'\linewidth')
    else:
        new_inner = re.sub(r'[lcr]', 'Y', inner)
    return (
        f'\\begin{{tsxtable}}\\begin{{tabularx}}{{\\linewidth}}'
        f'{{@{{}}{new_inner}@{{}}}}'
        f'{body}\\bottomrule\\noalign{{}}\n'
        f'\\end{{tabularx}}\\end{{tsxtable}}'
    )

src = re.sub(
    r'\\begin\{longtable\}\[\]\{@\{\}(.*?)@\{\}\}(.*?)\\end\{longtable\}',
    _rewrite_longtable,
    src,
    flags=re.DOTALL,
)

# Force \maketitle and \tableofcontents into single-column mode.
src = re.sub(
    r'(\\begin\{document\}\s*\n)(\\maketitle\s*\n\s*\n\{\s*\n\\setcounter\{tocdepth\}\{\d+\}\s*\n\\tableofcontents\s*\n\})',
    r'\1\\onecolumn\n\2\n\\twocolumn',
    src,
)

# Promote every figure float to span both columns.  Pandoc otherwise
# emits column-width figures, which makes every panel-heavy figure
# look squished.  figure* + dblfloatfix supports [!tbp] placement.
def _widen(m):
    block = m.group(0)
    block = block.replace(r'\begin{figure}',  r'\begin{figure*}[!tbp]', 1)
    block = block.replace(r'\end{figure}',    r'\end{figure*}',         1)
    return block

src = re.sub(
    r'\\begin\{figure\}.*?\\end\{figure\}',
    _widen,
    src,
    flags=re.DOTALL,
)

# Wrap long \texttt content (>=20 chars, contains /_. ) in \seqsplit
# so column-wide identifiers can break mid-token.  Skip texttt inside
# \texorpdfstring (section headings).
def _split_long_texttt(m):
    body = m.group(1)
    if len(body) < 20 or not any(c in body for c in '/_.'):
        return m.group(0)
    # Skip if we're inside a moving argument: \texorpdfstring{...}
    # (section heading, used inside TOC) or \caption{...} (figure or
    # table caption).  \seqsplit is fragile inside both.
    start = m.start()
    window = src[max(0, start - 600):start]
    for moving_cmd in (r'\texorpdfstring{', r'\caption{'):
        last = window.rfind(moving_cmd)
        if last == -1:
            continue
        tail = window[last + len(moving_cmd):]
        depth = 1
        for c in tail:
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    break
        if depth > 0:
            return m.group(0)
    return r'\texttt{\seqsplit{' + body + r'}}'

src = re.sub(r'\\texttt\{([^{}]+)\}', _split_long_texttt, src)

# Strip redundant section-divider blocks immediately adjacent to a
# floated figure (the preamble's \figdivider already supplies one).
src = re.sub(
    r'\\end\{figure\*?\}\s*\n\s*\n'
    r'\\begin\{center\}\\rule\{0\.5\\linewidth\}\{0\.5pt\}\\end\{center\}\s*\n',
    lambda m: m.group(0).split('\\begin{center}')[0],
    src,
)
src = re.sub(
    r'\\begin\{center\}\\rule\{0\.5\\linewidth\}\{0\.5pt\}\\end\{center\}\s*\n\s*\n'
    r'(\\begin\{figure\*?\})',
    r'\1',
    src,
)

# \FloatBarrier before each top-level \section so floats stay in
# their chapter.
src = re.sub(
    r'(\n)(\\section\{[^}]+\}\\label\{[^}]*\})',
    r'\1\\FloatBarrier\n\2',
    src,
)

open('paper.tex', 'w').write(src)
PYFIX

# 4c: xelatex twice (for TOC).
xelatex -interaction=nonstopmode -halt-on-error paper.tex > paper.xelatex.log 2>&1 || {
    echo "  xelatex pass 1 failed -- see $PAPER_DIR/paper.xelatex.log"
    exit 1
}
xelatex -interaction=nonstopmode -halt-on-error paper.tex > paper.xelatex.log 2>&1 || {
    echo "  xelatex pass 2 failed -- see $PAPER_DIR/paper.xelatex.log"
    exit 1
}

# Clean up aux/log clutter (keep .pdf, .tex, .build.md for diagnosis).
rm -f paper.aux paper.log paper.out paper.toc paper.xelatex.log

echo ""
echo "=== Build complete ==="
echo "PDF: $PAPER_DIR/paper.pdf ($(du -h "$PAPER_DIR/paper.pdf" | cut -f1))"
